### ISSUE TITLE
Modify AWSProvider to use boto directly

### ISSUE THREAD

**Issue by robparrott** [huit/nepho#108]
The AWS CLI is problematic, and we should switch to using boto directly.

Boto: 
- https://github.com/boto/boto
- http://docs.pythonboto.org/en/latest/

CloudFormation specific:
- http://docs.pythonboto.org/en/latest/ref/cloudformation.html

Boto should use the same config files the was CLI client (since it uses boot underneath) but we can also let users setup access credentials and default region using the nepho config commands.

**Comment by agperson** [comment]
Implemented by Rob, around about 2219964c82e18c7b89a3fa27b41a54aaee59ed91.
