### ISSUE TITLE
Let users setup AWS credentials via nepho configs

### ISSUE THREAD

**Issue by robparrott** [huit/nepho#109]
Instead of asking users to manage credentials via AWS_CONFIG_FILE we can allow users to set these within nepho itself.

Optionally use nepho to manage the AWS_CONFIG_FILE as well.

**Comment by agperson** [comment]
Since we are now using straight Boto, do we need to use BOTO_CONFIG?
Reference: https://code.google.com/p/boto/wiki/BotoConfig

**Comment by robparrott** [comment]
Well, many people will want to run nepho, then run the “aws” command-line tool to check on things. Making the two work together well, and making the AWS authored client tool the de-facto standard makes sense to me.

On November 14, 2013 at 2:06:34 PM, Daniel Silverman (notifications@github.com) wrote:

Since we are now using straight Boto, do we need to use BOTO_CONFIG?
Reference: https://code.google.com/p/boto/wiki/BotoConfig

**Comment by agperson** [comment]
Ok, so there is a way for Boto to read the .aws/config file?

**Comment by robparrott** [comment]
From the was command-line code, values are passed in in constructors to the boto lib calls.

I also think that if we passed in None values to these calls, boot would look for values in default places:

    http://boto.readthedocs.org/en/latest/boto_config_tut.html

**Comment by agperson** [comment]
Status update: users are now prompted to setup AWS credentials, but full awscli integration is pending.

**Comment by agperson** [comment]
Boto does not support reading the AWS CLI config file, and implementing that is a lot of trouble for very little gain.  I think what we have is good enough for now and until there is a compelling reason to implement more complex credential management I suggest we don't.  We can solve the profiles use-case through scoped parameters (i.e. a different AWSAccessKeyId for a different cloudlet or blueprint).
