### ISSUE TITLE
Finalize cloudlet structure

### ISSUE THREAD

**Issue by robparrott** [huit/nepho#112]
Danny's doc here:

Gets us 80% there, but I'd like to propose a couple additions.

Cloudlet structure:
- `cloudlet/`
  - `cloudlet.yaml`
  - `blueprints/*.yaml`
  - `resources/`
    - `patterns/`
      - `common/`
        - `aws/`
        - `provider_name/`
      - `my-blueprint/`
        - `vagrant/`
        - `another-provider/`
    - `hooks/`
      - `common/*`
      - `my-blueprint/`
  - `data/`

The `resources/` directory contains stuff that will be accessed and interpreted/consumed by nepho itself. This will include patterns and any hooks (since these are often injected into patterns in some fashion). The `data/` contains data that will only be treated as a BLOB by nepho, and though it may be pushed around by a provider (i.e. rsync to S3 bucket) will not be interpreted. Structure within this directory lis at the discretion of the user.

The distinction here is useful within nepho, because nepho needs a rudimentary resolution system for finding files such as patterns, pattern fragments, and any included hooks.

Resolution of a pattern file is as follows, order of precedence:
- `cloudlet/resources/patterns/[blueprint]/[provider]/[pattern_filename]`
- `cloudlet/resources/patterns/[blueprint]/[pattern_filename]`
- `cloudlet/resources/patterns/common/[provider]/[pattern_filename]`
- `cloudlet/resources/patterns/common/[pattern_filename]`

Similarly for hooks, if they need to be included and hence resolved.

**Comment by agperson** [comment]
Format 1 cloudlet basically finalized.
