### ISSUE TITLE
Define and implement standard way of bootstrapping that works for AWS.

### ISSUE THREAD

**Issue by robparrott** [huit/nepho#114]
Basically, define how we will control what the UserData section looks like on AWS and all other providers beyond vagrant (since many/most use UserData + cloud-init).

This is currently unspecified, and no deploys in AWS succeed according to CloudFormation.

**Comment by agperson** [comment]
This is now implemented.

**Comment by agperson** [comment]
Sorry, to be clear, this is now implemented in a basic form.  The bootstrapping/payload process works fine, but the Host template could use some cleanup.
