### ISSUE TITLE
interactive cloudlet namespace 

### ISSUE THREAD

**Issue by tfhartmann** [huit/nepho#117]
This is a feature post 1.0 for sure, but it would be really useful to "work inside" a particular cloudlet 

Something like this:

``` Shell
nepho use my-cloudlet
- Now using cloudlet - my-cloudlet -  
nepho(my-cloudlet) 
nepho(my-cloudlet) list 
/Users/alaric/.nepho/cloudlets
└── theforeman ( v0.0.1 )
```

That way you could also do stuff like without having to define a particular cloudlet 

``` Shell
[alaric@dhcp-128-103-62-80 nepho]$ nepho(theforeman) blueprint list 
└── theforeman ( v0.0.1 )
    └── development
        An example cloudlet that provides a Vagrant box running The Foreman.
[alaric@dhcp-128-103-62-80 nepho]$ 

```

**Comment by robparrott** [comment]
This could be easily done if we dropped the need for an interactive nepho environment.

And could be done for the blueprint too.

```
$> nepho use my-cloudlet my-blueprint
- Now using cloudlet/blueprint - my-cloudlet/my-blueprint -

$> nepho stack list
Stacks for my-cloudlet/my-blueprint: ....
```

To implement, we could use a config value or two:

```
working_cloudlet: my-cloudlent
working_blueprint: my-blueprint
```

Need to also implement:

```
nepho use none
```

**Comment by agperson** [comment]
Could we do this by setting an env variable and checking for it?
 NEPHO_CLOUDLET = my-cloudlet

On Wednesday, November 6, 2013, Rob Parrott wrote:

> This could be easily done if we dropped the need for an interactive nepho
> environment.
> 
> And could be done for the blueprint too.
> 
> $> nepho use my-cloudlet my-blueprint
> - Now using cloudlet/blueprint - my-cloudlet/my-blueprint - nepho
>   stack list Stacks for my-cloudlet/my-blueprint: ....
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/huit/nepho/issues/117#issuecomment-27878568
> .

## 

Daniel Silverman zeno@agblog.com
"I'd take the awe of understanding over the awe of ignorance any day." -
Douglas Adams

**Comment by tfhartmann** [comment]
I think with this merge 
https://github.com/huit/nepho/pull/131

We can close this issue, or should we keep it open and add eye-candy?
