### ISSUE TITLE
As a Stewie without a Github account, I want to be able to install cloudlets

### ISSUE THREAD

**Issue by agperson** [huit/nepho#126]
Currently it pulls as git@github.com (to setup remotes), but if the user does not have a Github account, or does not have it setup in, say, Cygwin, this fails with a permission denied error.

**Comment by agperson** [comment]
Here is Github's help on this (for someone with a Github account): https://help.github.com/articles/error-permission-denied-publickey

**Comment by tfhartmann** [comment]
How about maybe trying via ssh, and if that fails catch the error and try http? Maybe spit out something about not being able to do ssh due to (helpful github link)

**Comment by agperson** [comment]
I've started digging into this a bit, and its actually sorta complicated.  on Windows you might have the Github software installed, which bundles a git client and uses credentials over HTTPS, so you may not even have an SSH key, but still have a Github account and want to do checkins.

**Comment by agperson** [comment]
Ok, it sounds like this is a sensible approach. The registry will default to https URLs, and if the user wants to do ssh instead, there is an option for that.  For many users who will never be pushing cloudlet changes, this is fine.  For more advanced Clairs and Neds, they can set the option, or deal with HTTPS authentication (which, with proper software installed, is sometimes handled automatically anyway).

**Comment by tfhartmann** [comment]
:+1:
