### ISSUE TITLE
use `os.path` for path operations

### ISSUE THREAD

**Issue by hakamadare** [huit/nepho#140]
our Windows-using colleagues raise the point that assuming that `/` is the path separator leads to pain on the Windows platform.  brief research indicates that we should be using `os.path` (http://docs.python.org/2/library/os.path.html) for path operations, rather than doing regex matching and string interpolation etc.

classifying as an enhancement rather than a bug only because our support of the Windows platform is best-effort at the moment.

**Comment by agperson** [comment]
Where is os.path not used currently?  Just in the nepho_config code?

**Comment by agperson** [comment]
Nevermind, I'm going to try and quickly identify any offending places -- two found so far.

**Comment by hakamadare** [comment]
well, here's one example from the email thread:

```
paths = [path for path in cloudlet_paths if re.match(".*/" + name + "$", path)]
```

this could perhaps be implemented instead as:

```
paths = [path for path in cloudlet_paths if (os.path.split(path))[1] == name]
```

and i would expect that to work under Windows.
