### ISSUE TITLE
Vagrant provider should not use the "default" box

### ISSUE THREAD

**Issue by hakamadare** [huit/nepho#148]
i think i've seen issues with Vagrant behaving oddly when i try to use nepho to bring up a stack using the Vagrant provider, and i already have a Vagrant default box running.  maybe add a "InstanceName" parameter to the stock Vagrant template?

**Comment by robparrott** [comment]
I had begun doing that already.

Look at line 50 in vagrant_provider.py.

The problem is knowing the name to access it after it's up.

**Comment by agperson** [comment]
I ran a few tests of multi-VM vagrantfiles, and I couldn't identify the problem.  If we do not specify a box name and assume that `vagrant up` is what we want, vagrant takes care of this -- it generates a semi-random name if none is specified, and if one is specified in the Vagrantfile it uses that.  In multi-VM setups it works the same way.  I think we should let Vagrant handle this as it wants to and not override.  If I'm missing something that would make for a useful feature, feel free to re-open.
