### ISSUE TITLE
Create buildable nepho package for pypi

### ISSUE THREAD

**Issue by robparrott** [huit/nepho#17]
Make sure the dependencies are include at install time, rather than needing to be done by hand.

**Comment by agperson** [comment]
Related to #18

**Comment by agperson** [comment]
Started in 5097b1fc25df62fbc5f3b7767d9e2aae2b2b2dc5 -- requires a bit of refactoring.  Questions:
1. Should the yaml files be installed in /etc/nepho or similar, or should they live in the package
2. Does it make sense to move the YAML parsing out of aws/clidriver and up a level?
