### ISSUE TITLE
Let developers run nosetests

### ISSUE THREAD

**Issue by agperson** [huit/nepho#180]
When I do a `python setup.py develop` it installs flake8, nose, and coverage as `setup_requires`, which puts them local and clutters up my development directory, but doesn't actually seem to let me use/run them.  In contrast, if I run `pip -r ci/requirements.txt` as per `.travis.yml`, I am able to run the tests.  So I'm not sure if the setup_requires section is needed, or there is a different way with setuptools to automatically install those gems for develop mode?

**Comment by agperson** [comment]
OH hey!  I found https://nose.readthedocs.org/en/latest/api/commands.html which says to run `python setup.py nosetests` and that works!  I do still end up with junk in my development directory that maybe it is possible to hide somewhere else?

**Comment by tfhartmann** [comment]
what sort of stuff is it leaving around?

**Comment by agperson** [comment]
So @tfhartmann apparently included this information in the README in the tests/ directory.  Durr.  I'm an idiot.  Thanks Tim!
