### ISSUE TITLE
AWS Stack uniq names

### ISSUE THREAD

**Issue by tfhartmann** [huit/nepho#192]
Stacks should probably have some sort of uniq name, so that if I create an aws-single-host stack and a team member creates the same stack that they are able to create them without a conflict

**Comment by robparrott** [comment]
Use UUID locally, and each stack has a unique name vested by AWS.

**Comment by tfhartmann** [comment]
Yeah, but thats not all that human readable.... on the other hand... maybe it doesn't matter?

**Comment by agperson** [comment]
There is value in being able to find your stack without having to remember that it is 222C0289-915C-4861-BA98-451FEEB57E4B

**Comment by agperson** [comment]
Custom stack name can now be specified in as of PR #218
