### ISSUE TITLE
nepho issue when installing on Windows

### ISSUE THREAD

**Issue by vkojuharova** [huit/nepho#209]
Followed the instructions on the Nepho site
I have Windows 7 
Installed Python 2.7
Installed PIP

The first time I ran nepho stack deploy I got an error:

Stderr from the command:
/tmp/vagrant-shell: /var/lib/nepho/hooks/bootstrap: /bin/bash^M: bad interpreter: No such file or directory Vagrant exited with non-zero code, but your VM is likely running. Please use the status subcommand to check.

When I ran the same command subsequent times I did not get any error.

Second issue is when I run nepho stack access I get a Python.exe has stopped working.

At the same time the box is running and I can open the Virtual Box GUI and I can access vagrant ssh when I go to the  .nepho\cloudlets\nepho-example\resources\vagrant-single-host

**Comment by hakamadare** [comment]
our current conjecture is that Windows Git is [converting line endings on the fly](https://help.github.com/articles/dealing-with-line-endings#platform-windows) when checking out cloudlets.  perhaps a `.gitattributes` file in the cloudlet?
