### ISSUE TITLE
Problem running deploy

### ISSUE THREAD

**Issue by saperia** [huit/nepho#25]
nepho -E development deploy simple-website
Unknown key 'parameter_key' for parameter --, valid choices are: ParameterValue, ParameterKey
dhcp-128-103-65-117:~ saperia$ nepho -E development deploy simple-website
Unknown key 'parameter_key' for parameter --, valid choices are: ParameterValue, ParameterKey

**Comment by robparrott** [comment]
This was due to a change in the underlying aws-cli code. They change the command line options, and newer versions saw this error.

Fixed in master.
