### ISSUE TITLE
use jinja templating for CF templates

### ISSUE THREAD

**Issue by robparrott** [huit/nepho#3]
http://jinja.pocoo.org/docs/

**Comment by tfhartmann** [comment]
CF Templates are just JSON Dict's aren't they? Is there any need for a templating language in addition to just zipping dict's together?

**Comment by robparrott** [comment]
If think we will find that it'll be more useful without much overhead (basically include the python module) and should handle all the includes etc for us, as well as allow for if/then semantics if desired.

I could see a CF file that looks like

{% include 'common/Resources/AMIs.json %}
{% include 'common/Resources/VPC-3-tier.json %}

....

{% include 'common/Outputs/website-url.json %}

**Comment by robparrott** [comment]
Done.
