### ISSUE TITLE
Convert subnet options to an array

### ISSUE THREAD

**Issue by robparrott** [huit/nepho#34]
Currently, when specifying a subnet the templating stuff for AWS assumes that you are using a single subnet, and hence availability zone, for an autoscaling group and other such objects.

right now I;m adding a "subnet2" as well, but in general we'll want to make that an array subnets = [ subnet1, subnet2, ...] instead.

Will affect all pattern templates, so punting for now since I don't want to rock the boat quite yet.

**Comment by agperson** [comment]
No longer relevant.
