### ISSUE TITLE
Add/modify parameter to Fleet for the public entry IP, or hostname

### ISSUE THREAD

**Issue by robparrott** [huit/nepho#44]
Now that things are percolating back to the app tier better, found the issue that the information the backend tier has about its "external hostname" is really the hostname of the private tier's ELB. So we need an additional/different parameter to be passed, something like "NEPHO_PUBLIC_HOSTNAME" or similar.

Work would need to be done in the Fleet.json macro and the template files.

**Comment by robparrott** [comment]
We should also rename "NEPHO_EXTERNAL_HOSTNAME" and "NEPHO_BACKEND_HOSTNAME" to more general, in the sense that there actually represent the forward and backward communication endpoints hostname, and are not necessarily external or the backend. So something more relative, like "FORWARD" and "BACKWARD" or similar.

**Comment by agperson** [comment]
No longer relevant.
