### ISSUE TITLE
Version of python-requests conflict

### ISSUE THREAD

**Issue by robparrott** [huit/nepho#70]
The version of python-requests needed for the cloudformation helper scripts (`cfn-init`  in particular) is 1.1.0, while that for the latest aws-cli is >=1.2.x.

See:

```
https://forums.aws.amazon.com/thread.jspa?threadID=120833
```

This causes the build process to fail when you install the latest aws-cli. We need a solution that provides the functionality of aws-cli without the breakage.

**Comment by robparrott** [comment]
In particular, aws-cfn-bootstrap has requires: `requests>=0.11.1,<=1.1.0`

**Comment by robparrott** [comment]
This may now be an issue for the std lib instead.

**Comment by hakamadare** [comment]
my first thought is to do something analogous to Ruby's Bundler - nepho could come with its own private Python lib directory, in which all of nepho's dependencies are installed?

the Python "user" and "home" schemes may be relevant options?

http://docs.python.org/2/install/index.html#alternate-installation-the-user-scheme

**Comment by robparrott** [comment]
This is likely not an issue anymore
