### ISSUE TITLE
Implement "cloudlet uninstall" command

### ISSUE THREAD

**Issue by agperson** [huit/nepho#80]
- Remove a local cloudlet from disk
- If it is installed in multiple locations, prompt for which to remove, or all
- Prompt to remove overrides file(s), if they exist
- Prompt to destroy stacks based on this cloudlet, if they exist

**Comment by agperson** [comment]
Partially implemented in 57fd554c0e839e57fb64824a094d0bb8f800e0c3, but missing multi-location prompting, awareness of local/overrides, and stack awareness.

**Comment by agperson** [comment]
Implemented multi-location prompting in 1d36052f86a5f2893b02b602c181177c05d1d4c1.

**Comment by robparrott** [comment]
Danny, can you elaborate on the "overrides" file aspect?

**Comment by agperson** [comment]
Overrides, nee Local, now cloudlet sections in the config file.  So, delete the section upon deletion of the last installed version of the cloudlet (i.e. don't delete if it has been installed in multiple locations and we are not uninstalling all of them).

**Comment by agperson** [comment]
Remaining functionality (stack deletion) is tracked in #98.  I'm not sure there is a need to remove the scoped params on uninstall, what's the harm in keeping them around for future use?
