### ISSUE TITLE
Create unit tests for basic functionality

### ISSUE THREAD

**Issue by agperson** [huit/nepho#88]

**Comment by tfhartmann** [comment]
I think I'm going to start by just having it run through all the possible arg's

**Comment by tfhartmann** [comment]
Had a good conversation with derks from the cement IRC room, popping it here for a reference  

``` Shell
<derks> curious why under MyTestApp you are doing "app = cli.base.Nepho()"  when you are sub-classing from Nepho?
 <Pax> for no reason beside I just starting trying stuff...  and out of our working group, I'm probably the least pythonic :) 
 <derks> sure sure. ;)
 <derks> and also, where are you loading controllers/
 <derks> ?
 <derks> ah, duh you're doping that in the gist... but I don't see it in the git repo
 <Pax> ah! I see why I was using app = cli.base.Nepho() I was copying it from here https://github.com/huit/nepho/blob/master/bin/nepho
 <derks> ah, I see it...  the way you are registering your controllers/hooks here is no good
 <derks> the first thing that 'self.make_app()' does is 'self.reset_backend()'
 <derks> which clears all registered hook/handlers
 <Pax> oh! 
 <derks> you should be using CementApp.Meta.bootstrap to load controllers/hooks instead
 <Pax> so is there a good way to register the controllers/hooks for testing? 
 <derks> http://cement.readthedocs.org/en/latest/api/core/foundation/#cement.core.foundation.CementApp.Meta.bootstrap
 <derks> if you're app, or testapp has a Meta.bootstrap module if will load from there on runtim
 <Pax> so would that be something we should change in the code in general or only needed when we write tests? 
 <derks> for example, 'nepho.cli.bootstrap' .. and you'd import all of your hooks/controllers and register them there
 <derks> Cement loads nepho.cli.bootstrap, and then runs 'load()' if it exists
 <Pax> agh ok cool!
 <derks> works for both testing and regular
 <derks> for example, in the Boss project (that you probably used to start nepho):
 <derks> https://github.com/datafolklabs/boss/blob/master/boss/cli/bootstrap.py
 <derks> under load() you would register any hooks/handlers
 <Pax> ahh ok! I'll give that a try!! 
```

**Comment by agperson** [comment]
This is great info!  Tim do you want to implement this or would you like me
to?

On Tuesday, November 19, 2013, Tim Hartmann wrote:

> Had a good conversation with derks from the cement IRC room, popping it
> here for a reference
> 
> <derks> curious why under MyTestApp you are doing "app = cli.base.Nepho()"  when you are sub-classing from Nepho?
>  <Pax> for no reason beside I just starting trying stuff...  and out of our working group, I'm probably the least pythonic :)
>  <derks> sure sure. ;)
>  <derks> and also, where are you loading controllers/
>  <derks> ?
>  <derks> ah, duh you're doping that in the gist... but I don't see it in the git repo
>  <Pax> ah! I see why I was using app = cli.base.Nepho() I was copying it from here https://github.com/huit/nepho/blob/master/bin/nepho
>  <derks> ah, I see it...  the way you are registering your controllers/hooks here is no good
>  <derks> the first thing that 'self.make_app()' does is 'self.reset_backend()'
>  <derks> which clears all registered hook/handlers
>  <Pax> oh!
>  <derks> you should be using CementApp.Meta.bootstrap to load controllers/hooks instead
>  <Pax> so is there a good way to register the controllers/hooks for testing?
>  <derks> http://cement.readthedocs.org/en/latest/api/core/foundation/#cement.core.foundation.CementApp.Meta.bootstrap
>  <derks> if you're app, or testapp has a Meta.bootstrap module if will load from there on runtim
>  <Pax> so would that be something we should change in the code in general or only needed when we write tests?
>  <derks> for example, 'nepho.cli.bootstrap' .. and you'd import all of your hooks/controllers and register them there
>  <derks> Cement loads nepho.cli.bootstrap, and then runs 'load()' if it exists
>  <Pax> agh ok cool!
>  <derks> works for both testing and regular
>  <derks> for example, in the Boss project (that you probably used to start nepho):
>  <derks> https://github.com/datafolklabs/boss/blob/master/boss/cli/bootstrap.py
>  <derks> under load() you would register any hooks/handlers
>  <Pax> ahh ok! I'll give that a try!!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/huit/nepho/issues/88#issuecomment-28846151
> .

## 

Daniel Silverman zeno@agblog.com
"I'd take the awe of understanding over the awe of ignorance any day." -
Douglas Adams

**Comment by tfhartmann** [comment]
Actually I'd like to take a swing at it! I think I'll be a good learning experience! I'll open a branch in huit/nepho for the work!

**Comment by tfhartmann** [comment]
This is totally done! We as a team should continue to write good tests however!
